language: generic
dist: bionic
before_install:
- wget https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key
  add - && sudo sh -c "echo deb https://download.virtualbox.org/virtualbox/debian
  bionic contrib >> /etc/apt/sources.list" && sudo apt-get update && sudo apt-get
  install build-essential gcc make linux-headers-$(uname -r) virtualbox-6.0 && sudo
  usermod -aG vboxusers $(whoami)
- mkdir output-virtualbox-iso && pushd output-virtualbox-iso && wget --progress=dot:giga https://clovervm.ams3.digitaloceanspaces.com/base-focal.ova -O clover-devel.ova
  && popd
- sudo apt install -y xvfb
script:
- "xvfb-run ./build.sh"
# deploy:
#   provider: s3
#   access_key_id: XOJXX4IOM66XN7VZAFYX
#   secret_access_key: $S3_SECRET_KEY
#   bucket: clovervm
#   local-dir: output-virtualbox-ovf
#   acl: public_read
#   on:
#     all_branches: true
#   skip_cleanup: true
#   endpoint: https://ams3.digitaloceanspaces.com
